# Generated by Django 6.0.7 on 2026-08-18 08:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nazwa')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
            ],
            options={
                'verbose_name': 'rodzaj uprawy',
                'verbose_name_plural': 'rodzaje upraw',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TECHNICAL', 'Problem techniczny'), ('DATA', 'Problem z danymi'), ('INTERFACE', 'Problem z interfejsem'), ('OTHER', 'Inny')], max_length=10, verbose_name='kategoria')),
                ('description', models.TextField(verbose_name='opis')),
                ('status', models.CharField(choices=[('NEW', 'Nowe'), ('IN_PROGRESS', 'W trakcie'), ('RESOLVED', 'Rozwiązane')], max_length=11, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'zgłoszenie błędu',
                'verbose_name_plural': 'zgłoszenia błędów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nazwa')),
                ('area_ha', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='powierzchnia (ha)')),
                ('soil_type', models.CharField(choices=[('SANDY', 'Gleba piaszczysta'), ('CLAY', 'Gleba gliniasta'), ('LOAMY', 'Gleba ilasta'), ('SILT', 'Gleba pyłowa'), ('PEAT', 'Gleba torfowa'), ('OTHER', 'Inna')], max_length=10, verbose_name='rodzaj gleby')),
                ('parcel_identifier', models.CharField(blank=True, max_length=100, verbose_name='identyfikator działki')),
                ('location_method', models.CharField(choices=[('ADDRESS', 'Adres'), ('GPS', 'Współrzędne GPS'), ('MAP', 'Punkt na mapie'), ('PARCEL', 'Identyfikator działki')], max_length=10, verbose_name='metoda lokalizacji')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adres')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='szerokość geograficzna')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='długość geograficzna')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL, verbose_name='właściciel')),
            ],
            options={
                'verbose_name': 'pole rolne',
                'verbose_name_plural': 'pola rolne',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='rok sezonu')),
                ('status', models.CharField(choices=[('PLANNED', 'Planowana'), ('ACTIVE', 'Aktywna'), ('COMPLETED', 'Zakończona')], max_length=10, verbose_name='status')),
                ('sowing_date', models.DateField(blank=True, null=True, verbose_name='data siewu')),
                ('planned_harvest_date', models.DateField(blank=True, null=True, verbose_name='planowana data zbioru')),
                ('notes', models.TextField(blank=True, verbose_name='notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultivations', to='core.crop', verbose_name='rodzaj uprawy')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivations', to='core.field', verbose_name='pole')),
            ],
            options={
                'verbose_name': 'uprawa',
                'verbose_name_plural': 'uprawy',
                'ordering': ['-season_year', 'field__name', 'crop__name'],
            },
        ),
        migrations.CreateModel(
            name='FieldWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('PLOWING', 'Orka'), ('SOWING', 'Siew'), ('FERTILIZING', 'Nawożenie'), ('WATERING', 'Nawadnianie'), ('WEEDING', 'Odchwaszczanie'), ('OTHER', 'Inna')], max_length=12, verbose_name='rodzaj pracy')),
                ('work_date', models.DateField(verbose_name='data wykonania')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='koszt')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('cultivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='core.cultivation', verbose_name='uprawa')),
            ],
            options={
                'verbose_name': 'wykonana praca',
                'verbose_name_plural': 'wykonane prace',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(verbose_name='data zbioru')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='ilość')),
                ('unit', models.CharField(choices=[('KG', 'kg'), ('T', 't')], max_length=2, verbose_name='jednostka')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='przychód')),
                ('harvest_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='koszt zbioru')),
                ('notes', models.TextField(blank=True, verbose_name='notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('cultivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='core.cultivation', verbose_name='uprawa')),
            ],
            options={
                'verbose_name': 'zbiór',
                'verbose_name_plural': 'zbiory',
                'ordering': ['-harvest_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Spraying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spraying_date', models.DateField(verbose_name='data oprysku')),
                ('product_name', models.CharField(max_length=150, verbose_name='nazwa środka')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='ilość')),
                ('unit', models.CharField(choices=[('L', 'l'), ('ML', 'ml'), ('KG', 'kg'), ('G', 'g')], max_length=2, verbose_name='jednostka')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='koszt')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('cultivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprayings', to='core.cultivation', verbose_name='uprawa')),
            ],
            options={
                'verbose_name': 'oprysk',
                'verbose_name_plural': 'opryski',
                'ordering': ['-spraying_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(condition=models.Q(('area_ha__gt', 0)), name='core_field_area_ha_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='core_field_unique_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='cultivation',
            constraint=models.UniqueConstraint(fields=('field', 'crop', 'season_year'), name='core_cultivation_unique_field_crop_season'),
        ),
        migrations.AddConstraint(
            model_name='fieldwork',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='core_fieldwork_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='harvest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='core_harvest_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='harvest',
            constraint=models.CheckConstraint(condition=models.Q(('revenue__gte', 0)), name='core_harvest_revenue_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='harvest',
            constraint=models.CheckConstraint(condition=models.Q(('harvest_cost__gte', 0)), name='core_harvest_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='spraying',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='core_spraying_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='spraying',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='core_spraying_cost_gte_zero'),
        ),
    ]
