# Generated by Django 6.0.7 on 2026-09-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='disposition',
            field=models.CharField(choices=[('SOLD', 'Sprzedany'), ('STORED', 'Pozostawiony w magazynie'), ('DISCARDED', 'Strata / zutylizowany')], default='SOLD', max_length=10, verbose_name='przeznaczenie zbioru'),
        ),
        migrations.AddConstraint(
            model_name='harvest',
            constraint=models.CheckConstraint(condition=models.Q(('disposition', 'SOLD'), ('revenue', 0), _connector='OR'), name='core_harvest_unsold_revenue_zero'),
        ),
    ]
