# Generated by Django 6.0.7 on 2026-10-07 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_harvest_disposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivation',
            name='season_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2100)], verbose_name='rok sezonu'),
        ),
    ]
