# Generated by Django 6.0.7 on 2026-10-08 15:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cultivation_season_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['name'], 'verbose_name': 'crop type', 'verbose_name_plural': 'crop types'},
        ),
        migrations.AlterModelOptions(
            name='cultivation',
            options={'ordering': ['-season_year', 'field__name', 'crop__name'], 'verbose_name': 'cultivation', 'verbose_name_plural': 'cultivations'},
        ),
        migrations.AlterModelOptions(
            name='errorreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'error report', 'verbose_name_plural': 'error reports'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['name'], 'verbose_name': 'field', 'verbose_name_plural': 'fields'},
        ),
        migrations.AlterModelOptions(
            name='fieldwork',
            options={'ordering': ['-work_date', '-created_at'], 'verbose_name': 'field work', 'verbose_name_plural': 'field works'},
        ),
        migrations.AlterModelOptions(
            name='harvest',
            options={'ordering': ['-harvest_date', '-created_at'], 'verbose_name': 'harvest', 'verbose_name_plural': 'harvests'},
        ),
        migrations.AlterModelOptions(
            name='spraying',
            options={'ordering': ['-spraying_date', '-created_at'], 'verbose_name': 'spraying', 'verbose_name_plural': 'sprayings'},
        ),
        migrations.AlterField(
            model_name='crop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cultivation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='cultivation',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultivations', to='core.crop', verbose_name='crop type'),
        ),
        migrations.AlterField(
            model_name='cultivation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivations', to='core.field', verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='cultivation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='cultivation',
            name='planned_harvest_date',
            field=models.DateField(blank=True, null=True, verbose_name='planned harvest date'),
        ),
        migrations.AlterField(
            model_name='cultivation',
            name='season_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2100)], verbose_name='season year'),
        ),
        migrations.AlterField(
            model_name='cultivation',
            name='sowing_date',
            field=models.DateField(blank=True, null=True, verbose_name='sowing date'),
        ),
        migrations.AlterField(
            model_name='cultivation',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='category',
            field=models.CharField(choices=[('TECHNICAL', 'Technical problem'), ('DATA', 'Data problem'), ('INTERFACE', 'Interface problem'), ('OTHER', 'Other')], max_length=10, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved')], max_length=11, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='field',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='field',
            name='area_ha',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='area (ha)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='field',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='field',
            name='location_method',
            field=models.CharField(choices=[('ADDRESS', 'Address'), ('GPS', 'GPS coordinates'), ('MAP', 'Point on a map'), ('PARCEL', 'Parcel identifier')], max_length=10, verbose_name='location method'),
        ),
        migrations.AlterField(
            model_name='field',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='field',
            name='parcel_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='parcel identifier'),
        ),
        migrations.AlterField(
            model_name='field',
            name='soil_type',
            field=models.CharField(choices=[('SANDY', 'Sandy soil'), ('CLAY', 'Clay soil'), ('LOAMY', 'Loamy soil'), ('SILT', 'Silt soil'), ('PEAT', 'Peat soil'), ('OTHER', 'Other')], max_length=10, verbose_name='soil type'),
        ),
        migrations.AlterField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='fieldwork',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='fieldwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='fieldwork',
            name='cultivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='core.cultivation', verbose_name='cultivation'),
        ),
        migrations.AlterField(
            model_name='fieldwork',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='fieldwork',
            name='work_date',
            field=models.DateField(verbose_name='work date'),
        ),
        migrations.AlterField(
            model_name='fieldwork',
            name='work_type',
            field=models.CharField(choices=[('PLOWING', 'Plowing'), ('SOWING', 'Sowing'), ('FERTILIZING', 'Fertilizing'), ('WATERING', 'Watering'), ('WEEDING', 'Weeding'), ('OTHER', 'Other')], max_length=12, verbose_name='work type'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='cultivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='core.cultivation', verbose_name='cultivation'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='disposition',
            field=models.CharField(choices=[('SOLD', 'Sold'), ('STORED', 'Kept in storage'), ('DISCARDED', 'Loss / discarded')], default='SOLD', max_length=10, verbose_name='harvest disposition'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='harvest_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='harvest cost'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='harvest_date',
            field=models.DateField(verbose_name='harvest date'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='revenue'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='unit',
            field=models.CharField(choices=[('KG', 'kg'), ('T', 't')], max_length=2, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='spraying',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='spraying',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='spraying',
            name='cultivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprayings', to='core.cultivation', verbose_name='cultivation'),
        ),
        migrations.AlterField(
            model_name='spraying',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='spraying',
            name='product_name',
            field=models.CharField(max_length=150, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='spraying',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='spraying',
            name='spraying_date',
            field=models.DateField(verbose_name='spraying date'),
        ),
        migrations.AlterField(
            model_name='spraying',
            name='unit',
            field=models.CharField(choices=[('L', 'l'), ('ML', 'ml'), ('KG', 'kg'), ('G', 'g')], max_length=2, verbose_name='unit'),
        ),
    ]
