from django.urls import path

from .views import (
    CultivationCreateView,
    CultivationDeleteView,
    CultivationDetailView,
    CultivationListView,
    CultivationUpdateView,
    ErrorReportCreateView,
    ErrorReportDetailView,
    ErrorReportListView,
    FieldCreateView,
    FieldDeleteView,
    FieldDetailView,
    FieldListView,
    FieldUpdateView,
    FieldWorkCreateView,
    FieldWorkDeleteView,
    FieldWorkDetailView,
    FieldWorkListView,
    FieldWorkUpdateView,
    HarvestCreateView,
    HarvestDeleteView,
    HarvestDetailView,
    HarvestListView,
    HarvestUpdateView,
    LoginView,
    LogoutView,
    ProfileView,
    RegisterView,
    ReportDashboardView,
    SprayingCreateView,
    SprayingDeleteView,
    SprayingDetailView,
    SprayingListView,
    SprayingUpdateView,
    FieldReportView,
    CultivationReportView,
)

app_name = "core"

urlpatterns = [
    path("accounts/register/", RegisterView.as_view(), name="register"),
    path("accounts/login/", LoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/profile/", ProfileView.as_view(), name="profile"),
    path("fields/", FieldListView.as_view(), name="field_list"),
    path("fields/add/", FieldCreateView.as_view(), name="field_create"),
    path("fields/<int:pk>/", FieldDetailView.as_view(), name="field_detail"),
    path("fields/<int:pk>/edit/", FieldUpdateView.as_view(), name="field_update"),
    path("fields/<int:pk>/delete/", FieldDeleteView.as_view(), name="field_delete"),
    path("cultivations/", CultivationListView.as_view(), name="cultivation_list"),
    path("cultivations/add/", CultivationCreateView.as_view(), name="cultivation_create"),
    path(
        "cultivations/<int:pk>/",
        CultivationDetailView.as_view(),
        name="cultivation_detail",
    ),
    path(
        "cultivations/<int:pk>/edit/",
        CultivationUpdateView.as_view(),
        name="cultivation_update",
    ),
    path(
        "cultivations/<int:pk>/delete/",
        CultivationDeleteView.as_view(),
        name="cultivation_delete",
    ),
    path("works/", FieldWorkListView.as_view(), name="fieldwork_list"),
    path("works/add/", FieldWorkCreateView.as_view(), name="fieldwork_create"),
    path("works/<int:pk>/", FieldWorkDetailView.as_view(), name="fieldwork_detail"),
    path("works/<int:pk>/edit/", FieldWorkUpdateView.as_view(), name="fieldwork_update"),
    path("works/<int:pk>/delete/", FieldWorkDeleteView.as_view(), name="fieldwork_delete"),
    path("sprayings/", SprayingListView.as_view(), name="spraying_list"),
    path("sprayings/add/", SprayingCreateView.as_view(), name="spraying_create"),
    path("sprayings/<int:pk>/", SprayingDetailView.as_view(), name="spraying_detail"),
    path("sprayings/<int:pk>/edit/", SprayingUpdateView.as_view(), name="spraying_update"),
    path("sprayings/<int:pk>/delete/", SprayingDeleteView.as_view(), name="spraying_delete"),
    path("harvests/", HarvestListView.as_view(), name="harvest_list"),
    path("harvests/add/", HarvestCreateView.as_view(), name="harvest_create"),
    path("harvests/<int:pk>/", HarvestDetailView.as_view(), name="harvest_detail"),
    path("harvests/<int:pk>/edit/", HarvestUpdateView.as_view(), name="harvest_update"),
    path("harvests/<int:pk>/delete/", HarvestDeleteView.as_view(), name="harvest_delete"),
    path("reports/", ReportDashboardView.as_view(), name="report_dashboard"),
    path("reports/fields/<int:pk>/", FieldReportView.as_view(), name="field_report"),
    path(
        "reports/cultivations/<int:pk>/",
        CultivationReportView.as_view(),
        name="cultivation_report",
    ),
    path("error-reports/", ErrorReportListView.as_view(), name="error_report_list"),
    path(
        "error-reports/add/",
        ErrorReportCreateView.as_view(),
        name="error_report_create",
    ),
    path(
        "error-reports/<int:pk>/",
        ErrorReportDetailView.as_view(),
        name="error_report_detail",
    ),
]
